// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSchool_WEBAPI.Data;

#nullable disable

namespace SmartSchool_WEBAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("SmartSchool_WEBAPI.Models.Aluno", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Alunos");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "Marta",
                            Sobrenome = "Kent",
                            Telefone = "33225555"
                        },
                        new
                        {
                            ID = 2,
                            Nome = "Paula",
                            Sobrenome = "Isabela",
                            Telefone = "3354288"
                        },
                        new
                        {
                            ID = 3,
                            Nome = "Laura",
                            Sobrenome = "Antonia",
                            Telefone = "55668899"
                        },
                        new
                        {
                            ID = 4,
                            Nome = "Luíza",
                            Sobrenome = "Maria",
                            Telefone = "6565659"
                        },
                        new
                        {
                            ID = 5,
                            Nome = "Lucas",
                            Sobrenome = "Machado",
                            Telefone = "565685415"
                        },
                        new
                        {
                            ID = 6,
                            Nome = "Pedro",
                            Sobrenome = "Alvares",
                            Telefone = "456454545"
                        },
                        new
                        {
                            ID = 7,
                            Nome = "Paulo",
                            Sobrenome = "José",
                            Telefone = "9874512"
                        });
                });

            modelBuilder.Entity("SmartSchool_WEBAPI.Models.AlunoDisciplina", b =>
                {
                    b.Property<int>("AlunoID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisciplinaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("AlunoID", "DisciplinaID");

                    b.HasIndex("DisciplinaID");

                    b.ToTable("AlunosDisciplinas");

                    b.HasData(
                        new
                        {
                            AlunoID = 1,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 1,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 1,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 2,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 2,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 2,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 3,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 3,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 3,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoID = 4,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 4,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 4,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 5,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 5,
                            DisciplinaID = 5
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoID = 6,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 1
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 2
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 3
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 4
                        },
                        new
                        {
                            AlunoID = 7,
                            DisciplinaID = 5
                        });
                });

            modelBuilder.Entity("SmartSchool_WEBAPI.Models.Disciplina", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfessorID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("ProfessorID");

                    b.ToTable("Disciplinas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "Matemática",
                            ProfessorID = 1
                        },
                        new
                        {
                            ID = 2,
                            Nome = "Física",
                            ProfessorID = 2
                        },
                        new
                        {
                            ID = 3,
                            Nome = "Português",
                            ProfessorID = 3
                        },
                        new
                        {
                            ID = 4,
                            Nome = "Inglês",
                            ProfessorID = 4
                        },
                        new
                        {
                            ID = 5,
                            Nome = "Programação",
                            ProfessorID = 5
                        });
                });

            modelBuilder.Entity("SmartSchool_WEBAPI.Models.Professor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Professores");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Nome = "Lauro"
                        },
                        new
                        {
                            ID = 2,
                            Nome = "Roberto"
                        },
                        new
                        {
                            ID = 3,
                            Nome = "Ronaldo"
                        },
                        new
                        {
                            ID = 4,
                            Nome = "Rodrigo"
                        },
                        new
                        {
                            ID = 5,
                            Nome = "Alexandre"
                        });
                });

            modelBuilder.Entity("SmartSchool_WEBAPI.Models.AlunoDisciplina", b =>
                {
                    b.HasOne("SmartSchool_WEBAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartSchool_WEBAPI.Models.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");
                });

            modelBuilder.Entity("SmartSchool_WEBAPI.Models.Disciplina", b =>
                {
                    b.HasOne("SmartSchool_WEBAPI.Models.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("ProfessorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("SmartSchool_WEBAPI.Models.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
